// <auto-generated />
using System;
using DoWell.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoWell.Migrations
{
    [DbContext(typeof(DoWellContext))]
    [Migration("20250822161645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoWell.Models.Cell", b =>
                {
                    b.Property<int>("CellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CellId"));

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<bool>("IsBold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItalic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderline")
                        .HasColumnType("bit");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorksheetId")
                        .HasColumnType("int");

                    b.HasKey("CellId");

                    b.HasIndex("WorksheetId", "Row", "Column")
                        .IsUnique();

                    b.ToTable("Cells");

                    b.HasData(
                        new
                        {
                            CellId = 1,
                            Column = 0,
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 0,
                            Value = "Product",
                            WorksheetId = 1
                        },
                        new
                        {
                            CellId = 2,
                            Column = 1,
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 0,
                            Value = "Price",
                            WorksheetId = 1
                        },
                        new
                        {
                            CellId = 3,
                            Column = 2,
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 0,
                            Value = "Quantity",
                            WorksheetId = 1
                        },
                        new
                        {
                            CellId = 4,
                            Column = 0,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 1,
                            Value = "Laptop",
                            WorksheetId = 1
                        },
                        new
                        {
                            CellId = 5,
                            Column = 1,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 1,
                            Value = "999.99",
                            WorksheetId = 1
                        },
                        new
                        {
                            CellId = 6,
                            Column = 2,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 1,
                            Value = "5",
                            WorksheetId = 1
                        },
                        new
                        {
                            CellId = 7,
                            Column = 0,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 2,
                            Value = "Mouse",
                            WorksheetId = 1
                        },
                        new
                        {
                            CellId = 8,
                            Column = 1,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 2,
                            Value = "29.99",
                            WorksheetId = 1
                        },
                        new
                        {
                            CellId = 9,
                            Column = 2,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 2,
                            Value = "15",
                            WorksheetId = 1
                        });
                });

            modelBuilder.Entity("DoWell.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@dowell.com",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user1@dowell.com",
                            Username = "user1"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2@dowell.com",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("DoWell.Models.UserWorkbook", b =>
                {
                    b.Property<int>("UserWorkbookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserWorkbookId"));

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SharedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkbookId")
                        .HasColumnType("int");

                    b.HasKey("UserWorkbookId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkbookId");

                    b.ToTable("UserWorkbooks");

                    b.HasData(
                        new
                        {
                            UserWorkbookId = 1,
                            CanEdit = true,
                            SharedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1,
                            WorkbookId = 1
                        },
                        new
                        {
                            UserWorkbookId = 2,
                            CanEdit = true,
                            SharedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1,
                            WorkbookId = 2
                        },
                        new
                        {
                            UserWorkbookId = 3,
                            CanEdit = false,
                            SharedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            WorkbookId = 1
                        });
                });

            modelBuilder.Entity("DoWell.Models.Workbook", b =>
                {
                    b.Property<int>("WorkbookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkbookId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WorkbookId");

                    b.ToTable("Workbooks");

                    b.HasData(
                        new
                        {
                            WorkbookId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget 2024"
                        },
                        new
                        {
                            WorkbookId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sales Report"
                        });
                });

            modelBuilder.Entity("DoWell.Models.Worksheet", b =>
                {
                    b.Property<int>("WorksheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorksheetId"));

                    b.Property<int>("ColumnCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<int>("WorkbookId")
                        .HasColumnType("int");

                    b.HasKey("WorksheetId");

                    b.HasIndex("WorkbookId");

                    b.ToTable("Worksheets");

                    b.HasData(
                        new
                        {
                            WorksheetId = 1,
                            ColumnCount = 10,
                            Name = "Sheet1",
                            RowCount = 20,
                            WorkbookId = 1
                        },
                        new
                        {
                            WorksheetId = 2,
                            ColumnCount = 8,
                            Name = "Sheet2",
                            RowCount = 15,
                            WorkbookId = 1
                        },
                        new
                        {
                            WorksheetId = 3,
                            ColumnCount = 12,
                            Name = "Q1",
                            RowCount = 25,
                            WorkbookId = 2
                        });
                });

            modelBuilder.Entity("DoWell.Models.Cell", b =>
                {
                    b.HasOne("DoWell.Models.Worksheet", "Worksheet")
                        .WithMany("Cells")
                        .HasForeignKey("WorksheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worksheet");
                });

            modelBuilder.Entity("DoWell.Models.UserWorkbook", b =>
                {
                    b.HasOne("DoWell.Models.User", "User")
                        .WithMany("UserWorkbooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoWell.Models.Workbook", "Workbook")
                        .WithMany()
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("DoWell.Models.Worksheet", b =>
                {
                    b.HasOne("DoWell.Models.Workbook", "Workbook")
                        .WithMany("Worksheets")
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("DoWell.Models.User", b =>
                {
                    b.Navigation("UserWorkbooks");
                });

            modelBuilder.Entity("DoWell.Models.Workbook", b =>
                {
                    b.Navigation("Worksheets");
                });

            modelBuilder.Entity("DoWell.Models.Worksheet", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
