// <auto-generated />
using System;
using DoWell.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoWell.Migrations
{
    [DbContext(typeof(DoWellContext))]
    [Migration("20250828121817_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoWell.Models.Cell", b =>
                {
                    b.Property<int>("CellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CellId"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<string>("ForegroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FormatTemplateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItalic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderline")
                        .HasColumnType("bit");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkbookId")
                        .HasColumnType("int");

                    b.HasKey("CellId");

                    b.HasIndex("FormatTemplateId");

                    b.HasIndex("WorkbookId", "Row", "Column")
                        .IsUnique();

                    b.ToTable("Cells");

                    b.HasData(
                        new
                        {
                            CellId = 1,
                            BackgroundColor = "#4472C4",
                            Column = 0,
                            ForegroundColor = "#FFFFFF",
                            FormatTemplateId = 1,
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 0,
                            Value = "Product",
                            WorkbookId = 1
                        },
                        new
                        {
                            CellId = 2,
                            BackgroundColor = "#4472C4",
                            Column = 1,
                            ForegroundColor = "#FFFFFF",
                            FormatTemplateId = 1,
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 0,
                            Value = "Price",
                            WorkbookId = 1
                        },
                        new
                        {
                            CellId = 3,
                            BackgroundColor = "#4472C4",
                            Column = 2,
                            ForegroundColor = "#FFFFFF",
                            FormatTemplateId = 1,
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 0,
                            Value = "Quantity",
                            WorkbookId = 1
                        },
                        new
                        {
                            CellId = 4,
                            BackgroundColor = "#FFFFFF",
                            Column = 0,
                            ForegroundColor = "#000000",
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 1,
                            Value = "Laptop",
                            WorkbookId = 1
                        },
                        new
                        {
                            CellId = 5,
                            BackgroundColor = "#F2F2F2",
                            Column = 1,
                            ForegroundColor = "#0000FF",
                            FormatTemplateId = 2,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 1,
                            Value = "999.99",
                            WorkbookId = 1
                        },
                        new
                        {
                            CellId = 6,
                            BackgroundColor = "#F2F2F2",
                            Column = 2,
                            ForegroundColor = "#0000FF",
                            FormatTemplateId = 2,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 1,
                            Value = "5",
                            WorkbookId = 1
                        },
                        new
                        {
                            CellId = 7,
                            BackgroundColor = "#FFFFFF",
                            Column = 0,
                            ForegroundColor = "#000000",
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 2,
                            Value = "Mouse",
                            WorkbookId = 1
                        },
                        new
                        {
                            CellId = 8,
                            BackgroundColor = "#F2F2F2",
                            Column = 1,
                            ForegroundColor = "#0000FF",
                            FormatTemplateId = 2,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 2,
                            Value = "29.99",
                            WorkbookId = 1
                        },
                        new
                        {
                            CellId = 9,
                            BackgroundColor = "#F2F2F2",
                            Column = 2,
                            ForegroundColor = "#0000FF",
                            FormatTemplateId = 2,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 2,
                            Value = "15",
                            WorkbookId = 1
                        });
                });

            modelBuilder.Entity("DoWell.Models.FormatTemplate", b =>
                {
                    b.Property<int>("FormatTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormatTemplateId"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("FontSize")
                        .HasColumnType("float");

                    b.Property<string>("ForegroundColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("IsBold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItalic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WorkbookId")
                        .HasColumnType("int");

                    b.HasKey("FormatTemplateId");

                    b.HasIndex("WorkbookId");

                    b.ToTable("FormatTemplates");

                    b.HasData(
                        new
                        {
                            FormatTemplateId = 1,
                            BackgroundColor = "#4472C4",
                            FontFamily = "Segoe UI",
                            FontSize = 12.0,
                            ForegroundColor = "#FFFFFF",
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Name = "Header Style",
                            WorkbookId = 1
                        },
                        new
                        {
                            FormatTemplateId = 2,
                            BackgroundColor = "#F2F2F2",
                            FontFamily = "Consolas",
                            FontSize = 11.0,
                            ForegroundColor = "#0000FF",
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Name = "Number Style",
                            WorkbookId = 1
                        },
                        new
                        {
                            FormatTemplateId = 3,
                            BackgroundColor = "#FFFF00",
                            FontFamily = "Segoe UI",
                            FontSize = 11.0,
                            ForegroundColor = "#000000",
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Name = "Highlight Style",
                            WorkbookId = 1
                        });
                });

            modelBuilder.Entity("DoWell.Models.Workbook", b =>
                {
                    b.Property<int>("WorkbookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkbookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastSavedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("WorkbookId");

                    b.ToTable("Workbooks");

                    b.HasData(
                        new
                        {
                            WorkbookId = 1,
                            Author = "DoWell User",
                            CreatedDate = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSavedDate = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sample Workbook"
                        });
                });

            modelBuilder.Entity("DoWell.Models.Cell", b =>
                {
                    b.HasOne("DoWell.Models.FormatTemplate", "FormatTemplate")
                        .WithMany("Cells")
                        .HasForeignKey("FormatTemplateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DoWell.Models.Workbook", "Workbook")
                        .WithMany("Cells")
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormatTemplate");

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("DoWell.Models.FormatTemplate", b =>
                {
                    b.HasOne("DoWell.Models.Workbook", "Workbook")
                        .WithMany("FormatTemplates")
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("DoWell.Models.FormatTemplate", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("DoWell.Models.Workbook", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("FormatTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
