// <auto-generated />
using DoWell.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoWell.Migrations
{
    [DbContext(typeof(DoWellContext))]
    [Migration("20250823161727_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoWell.Models.Cell", b =>
                {
                    b.Property<int>("CellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CellId"));

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<bool>("IsBold")
                        .HasColumnType("bit");

                    b.Property<bool>("IsItalic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderline")
                        .HasColumnType("bit");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CellId");

                    b.HasIndex("Row", "Column")
                        .IsUnique();

                    b.ToTable("Cells");

                    b.HasData(
                        new
                        {
                            CellId = 1,
                            Column = 0,
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 0,
                            Value = "Product"
                        },
                        new
                        {
                            CellId = 2,
                            Column = 1,
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 0,
                            Value = "Price"
                        },
                        new
                        {
                            CellId = 3,
                            Column = 2,
                            IsBold = true,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 0,
                            Value = "Quantity"
                        },
                        new
                        {
                            CellId = 4,
                            Column = 0,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 1,
                            Value = "Laptop"
                        },
                        new
                        {
                            CellId = 5,
                            Column = 1,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 1,
                            Value = "999.99"
                        },
                        new
                        {
                            CellId = 6,
                            Column = 2,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 1,
                            Value = "5"
                        },
                        new
                        {
                            CellId = 7,
                            Column = 0,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 2,
                            Value = "Mouse"
                        },
                        new
                        {
                            CellId = 8,
                            Column = 1,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 2,
                            Value = "29.99"
                        },
                        new
                        {
                            CellId = 9,
                            Column = 2,
                            IsBold = false,
                            IsItalic = false,
                            IsUnderline = false,
                            Row = 2,
                            Value = "15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
